service: service-health-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  bundle:
    linting: false

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-2

  environment:
    tableName: service-health-table

  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Scan
      - dynamodb:Query
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:DescribeTable
    Resource: "arn:aws:dynamodb:ap-southeast-2:*:*"

functions:

  create:
    handler: service/create_service.main
    events:
      - http:
          path: service
          method: post

  get:
    handler: service/get_service.main
    events:
      - http:
          path: service/{service_id}
          method: get

  list:
    handler: service/list_service.main
    events:
      - http:
          path: service
          method: get

  update:
    handler: service/update_service.main
    events:
      - http:
          path: notes/{service_id}
          method: put

  delete:
    handler: service/delete_service.main
    events:
      - http:
          path: notes/{service_id}
          method: delete